"""Measure real Linear server cold chunk loads and synchronous save latency."""
import json
from pathlib import Path
import re
import subprocess
import time

import linear_verification_chain as chain

TEST = chain.TEST
EVIDENCE = TEST / "chain-evidence-followups"
PROD_PASSWORD = Path("/etc/drewcraft/rcon-password")


def loaded_response(response: str) -> bool:
    """Minecraft returns the nested command output when execute succeeds."""
    return "test passed" in response.lower() or response.strip().lower().startswith("the time is ")


def pending_loaded_response(response: str) -> bool:
    """An empty RCON response is the normal result when `if loaded` is false."""
    return not response.strip() or "test failed" in response.lower()


FORCELoad_ACK_PHRASES = (
    "added",
    "force loaded",
    "force load",
    "marked chunk",
    "no chunks were marked",
)


def forceload_accepted(response: str) -> bool:
    """Accept observed `/forceload add` acknowledgements.

    Recorded production forms include 'Marked chunk [-177, 47] in Overworld
    to be force loaded' and 'No chunks were marked for force loading'.
    """
    text = response.lower()
    return any(phrase in text for phrase in FORCELoad_ACK_PHRASES)


def production_players():
    from rcon.source import Client
    with Client("127.0.0.1", 25575, passwd=PROD_PASSWORD.read_text().strip(), timeout=8) as client:
        return client.run("list")


def run(evidence: Path):
    global EVIDENCE
    EVIDENCE = evidence
    if EVIDENCE.exists():
        raise RuntimeError(f"Evidence already exists; inspect before retry: {EVIDENCE}")
    chain.reserve()
    player_report = production_players()
    if "There are 0 of a max of" not in player_report:
        raise RuntimeError(f"Production is occupied; refusing benchmark: {player_report}")

    stopped_pregen = False
    booted_test = False
    result = {"status": "RUNNING", "productionPlayers": player_report}
    EVIDENCE.mkdir()
    try:
        subprocess.run(["systemctl", "stop", "drewcraft-pregen"], check=True)
        stopped_pregen = True
        if not Path("/srv/drewcraft/linear-verification/runtime/world/region").is_dir():
            raise RuntimeError("Isolated Linear runtime world is missing")
        chain.boot_server()
        booted_test = True

        # Nine FULL chunks already generated by the passing bounded Chunky test.
        points = [(x, 80, z) for x in (-2824, -2808, -2792)
                  for z in (760, 776, 792)]
        start = time.monotonic()
        for x, y, z in points:
            response = chain.checked("forceload", "add", str(x), str(z))
            if not forceload_accepted(response):
                raise RuntimeError(f"Could not request saved chunk {x},{z}: {response}")

        deadline = time.monotonic() + 180
        pending = set(points)
        polls = 0
        while pending and time.monotonic() < deadline:
            for point in list(pending):
                response = chain.rcon("execute", "if", "loaded", *(str(v) for v in point),
                                      "run", "time", "query", "gametime")
                polls += 1
                # execute's conditional success returns the nested command's
                # output ("The time is N"), not Brigadier's generic test text.
                if loaded_response(response):
                    pending.remove(point)
                elif not pending_loaded_response(response):
                    raise RuntimeError(f"Unexpected loaded-chunk query: {response}")
            if pending:
                time.sleep(1)
        if pending:
            raise TimeoutError(f"Linear chunks did not all load within 180 seconds: {sorted(pending)}")
        result["coldProcessChunkLoadSeconds"] = round(time.monotonic() - start, 3)
        result["loadedChunks"] = len(points)
        result["chunkLoadPolls"] = polls

        save_times = []
        for _ in range(5):
            began = time.monotonic()
            response = chain.checked("save-all", "flush")
            if "Saved the game" not in response:
                raise RuntimeError("Minecraft did not acknowledge save-all flush")
            save_times.append(round(time.monotonic() - began, 3))
        result["saveAllFlushSeconds"] = save_times
        result["saveAllMedianSeconds"] = sorted(save_times)[len(save_times) // 2]
        result["scope"] = "Real Java/NeoForge server; one process-cold load of nine saved Linear chunks and five flushes. Not a flight/TPS soak."
        chain.no_fallbacks()
        result["noAnvilFallbackFiles"] = True
        result["status"] = "PASS"
        return result
    except BaseException as error:
        result["status"] = "FAILED"
        result["error"] = f"{type(error).__name__}: {error}"
        raise
    finally:
        result["finishedUnix"] = time.time()
        if booted_test:
            try:
                chain.rcon("forceload", "remove", "all")
            except Exception as exc:
                result["forceLoadCleanupError"] = str(exc)
                result["status"] = "FAILED_CLEANUP"
            try:
                chain.stop_server()
            except Exception as exc:
                result["testStopError"] = str(exc)
                result["status"] = "FAILED_CLEANUP"
        if stopped_pregen:
            subprocess.run(["systemctl", "start", "drewcraft-pregen"], check=True)
        (EVIDENCE / "java-runtime.json").write_text(json.dumps(result, indent=2) + "\n")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-id", required=True)
    run_id = parser.parse_args().run_id
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]{0,31}", run_id):
        raise ValueError("Invalid run id")
    print(json.dumps(run(TEST / ("chain-evidence-followups-" + run_id)), indent=2), flush=True)
