allow-flight=true
difficulty=normal
enable-command-block=false
enable-rcon=true
rcon.port=25575
rcon.ip=127.0.0.1
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
gamemode=survival
level-name=world
max-players=10
motd=DrewCraft V1 Survival
online-mode=true
pvp=true
simulation-distance=8
spawn-protection=16
view-distance=10
white-list=true
